version: '3'
services:
  cache:
    image: redis
    container_name: cache
    ports:
      - "6380:6379"
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    volumes:
      - ./logs/mysql:/var/log:rw
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php7:
    image: php72-fpm
    depends_on:
      - mysql
    build:
      context: ./docker-files/php7/
      dockerfile: Dockerfile
    container_name: php7
    volumes:
      - ./storage/app:/app
      - ./storage/logs/php7:/var/log:rw
    ports:
      - "9001:9000"
    links:
      - mysql:mysql
      - cache:cache
  web:
    image: nginx
    container_name: web
    depends_on:
      - php7
    volumes:
      - ./storage/app:/app
      - ./conf/nginx_default.conf:/etc/nginx/conf.d/nginx_default.conf:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - php7:php7
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"
  