version: '3'
services:
  cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    volumes:
      - ${PWD}/logs/mysql:/var/log:rw
      - ${PWD}/storage/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  php7:
    image: php72-fpm
    build:
      context: ${PWD}/docker-files/php7/
      dockerfile: Dockerfile
    container_name: php7
    volumes:
      - ${PWD}/public:/var/www
      - ${PWD}/storage/logs/php7:/var/log:rw
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - cache:cache
  web:
    image: nginx
    container_name: web
    volumes:
      - ${PWD}/public:/var/www
      - ${PWD}/conf/nginx_default.conf:/etc/nginx/conf.d/nginx_default.conf:ro
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - php7:php7
    ports:
      - "8080:80"
      - "8043:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"
  